kind: pipeline
name: default
type: docker
steps:
  - name: build
    image: plugins/docker
    settings:
      username: k3env
      password:
        from_secret: DOCKER_PASSWORD
      repo: k3env/kvdns
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
