kind: pipeline
name: dev
type: docker
steps:
  - name: build
    image: plugins/docker
    settings:
      username: k3env
      password:
        from_secret: DOCKER_PASSWORD
      repo: k3env/kvdns
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
trigger:
  event:
    - push
    - promote
    - custom
---
kind: pipeline
name: release
type: docker
steps:
  - name: build
    image: plugins/docker
    settings:
      username: k3env
      password:
        from_secret: DOCKER_PASSWORD
      repo: k3env/kvdns
      tags:
        - ${DRONE_TAG}
        - stable
trigger:
  event:
    - tag
