name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "::set-output name=short_sha::$calculatedSha"
    - name: Build the Docker image
      run: docker build . --tag k3env/kvdns:${{ steps.vars.outputs.short_sha }} && docker push k3env/kvdns:${{ steps.vars.outputs.short_sha }}
